personal_project_Mansi: To Do List
 
 
name: Mansi

repo_names:
  - To Do List


# Provide any URLs for your Videos
10-ux-ui-criticism:
  - https://youtu.be/pgNJyIe2iII


# Provide any URLs for your Data Models assignment
11-models-from-data:
  - 

project-check-in-1: https://github.com/mansivashisth/ATLAS-iOS-Fall-22/issues/1#issue-1411889863
